#!/usr/bin/env python3
"""Generate tuning_data.h from the RPi calibrated tuning file for the IMX415
(reference/imx415-tuning-pisp.json): CCM table, AWB CT curve, ALSC tables.

Run from tools/cuda_debayer/:  python3 gen_tuning.py
"""
import json
import os

SRC = os.path.join(os.path.dirname(__file__), "..", "..", "reference",
                   "imx415-tuning-pisp.json")
DST = os.path.join(os.path.dirname(__file__), "tuning_data.h")


def fmt_floats(vals, per_line=8, indent="\t"):
    lines = []
    for i in range(0, len(vals), per_line):
        lines.append(indent + ", ".join("%.5ff" % v
                                        for v in vals[i:i + per_line]) + ",")
    return "\n".join(lines)


def main():
    with open(SRC) as f:
        data = json.load(f)
    alg = {}
    for a in data["algorithms"]:
        alg.update(a)

    awb = alg["rpi.awb"]
    ccm = alg["rpi.ccm"]["ccms"]
    alsc = alg["rpi.alsc"]

    out = []
    out.append("/* Generated by gen_tuning.py from "
               "reference/imx415-tuning-pisp.json - do not edit. */")
    out.append("#ifndef TUNING_DATA_H")
    out.append("#define TUNING_DATA_H")
    out.append("")

    # CCM table
    out.append("struct CcmEntry {\n\tfloat ct;\n\tfloat m[9];\n};")
    out.append("static const CcmEntry ccm_table[] = {")
    for e in ccm:
        m = ", ".join("%.5ff" % v for v in e["ccm"])
        out.append("\t{ %.1ff, { %s } }," % (e["ct"], m))
    out.append("};")
    out.append("#define CCM_TABLE_LEN "
               "(sizeof(ccm_table) / sizeof(ccm_table[0]))")
    out.append("")

    # AWB CT curve: (ct, r, b) with r = R/G, b = B/G of a neutral patch
    curve = awb["ct_curve"]
    out.append("struct CtPoint {\n\tfloat ct, r, b;\n};")
    out.append("static const CtPoint ct_curve[] = {")
    for i in range(0, len(curve), 3):
        out.append("\t{ %.1ff, %.5ff, %.5ff }," % tuple(curve[i:i + 3]))
    out.append("};")
    out.append("#define CT_CURVE_LEN (sizeof(ct_curve) / sizeof(ct_curve[0]))")
    out.append("#define AWB_TRANSVERSE_POS %.5ff" % awb["transverse_pos"])
    out.append("#define AWB_TRANSVERSE_NEG %.5ff" % awb["transverse_neg"])
    out.append("")

    # ALSC: 32x32 gain grids for Cr (R/G) and Cb (B/G) at two CTs,
    # plus a luminance grid applied at reduced strength.
    out.append("#define ALSC_GRID 32")
    out.append("#define ALSC_LUM_STRENGTH %.3ff" % alsc["luminance_strength"])
    for chan in ("Cr", "Cb"):
        cals = alsc["calibrations_" + chan]
        assert len(cals) == 2, "expected 2 ALSC calibrations per channel"
        for cal in cals:
            assert len(cal["table"]) == 1024
            out.append("static const float alsc_%s_%d[1024] = {"
                       % (chan.lower(), cal["ct"]))
            out.append(fmt_floats(cal["table"]))
            out.append("};")
    lums = alsc["luminance_lut"]
    assert len(lums) == 1024
    out.append("static const float alsc_lum[1024] = {")
    out.append(fmt_floats(lums))
    out.append("};")
    ct_lo = alsc["calibrations_Cr"][0]["ct"]
    ct_hi = alsc["calibrations_Cr"][1]["ct"]
    out.append("#define ALSC_CT_LO %d" % ct_lo)
    out.append("#define ALSC_CT_HI %d" % ct_hi)
    out.append("")
    out.append("#endif /* TUNING_DATA_H */")

    with open(DST, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote %s" % DST)


if __name__ == "__main__":
    main()
