#!/usr/bin/env bash
# Generate include/nvidia/conftest.h for a standalone (out of the nvidia-oot
# tree) build of nv_imx415.ko.
#
# NVIDIA's OOT headers include <nvidia/conftest.h>, a file their build system
# generates by test-compiling snippets against the target kernel. The
# installed L4T header packages do NOT ship it. The macros matter: one of
# them (NV_TEGRA_PMC_IO_PAD_POWER_ENABLE_PRESENT) adds a field to
# struct camera_common_data, i.e. it changes the layout of a struct shared
# with the prebuilt tegra-camera.ko. Guessing is not an option, so each
# macro is decided the way NVIDIA decides it: by compiling a probe snippet
# with the kernel's own Kbuild flags (a single-object M= build).
#
# Usage: KDIR=/lib/modules/$(uname -r)/build ./conftest.sh <output header>
set -eu

OUT="${1:-include/nvidia/conftest.h}"
KDIR="${KDIR:-/lib/modules/$(uname -r)/build}"
[ -f "$KDIR/Makefile" ] || { echo "conftest: no kernel build tree at $KDIR" >&2; exit 1; }

TMP=$(mktemp -d "${TMPDIR:-/tmp}/imx415-conftest.XXXXXX")
trap 'rm -rf "$TMP"' EXIT

# compile <name> <snippet>: 0 if the snippet compiles with the kernel's flags
compile() {
	local name=$1 code=$2
	mkdir -p "$TMP/$name"
	printf '%s\n' "$code" > "$TMP/$name/probe.c"
	printf 'obj-y := probe.o\n' > "$TMP/$name/Makefile"
	make -C "$KDIR" M="$TMP/$name" probe.o >"$TMP/$name/log" 2>&1
}

# Control: the harness itself must work, or every test below would read as
# "absent" and silently produce a wrong header.
compile ok '#include <linux/i2c.h>
int conftest_ok(void);
int conftest_ok(void) { return 0; }' \
	|| { echo "conftest: control snippet failed to compile - kernel headers unusable:" >&2; cat "$TMP/ok/log" >&2; exit 1; }

decide() { # <macro> <name> <snippet>
	if compile "$2" "$3"; then
		echo "#define $1"
		echo "conftest: $1 = present" >&2
	else
		echo "#undef $1"
		echo "conftest: $1 = absent" >&2
	fi
}

mkdir -p "$(dirname "$OUT")"
{
	echo "/* Generated by conftest.sh against $KDIR - do not edit. */"
	echo "#ifndef _NV_IMX415_CONFTEST_H"
	echo "#define _NV_IMX415_CONFTEST_H"

	# i2c_driver.probe lost its i2c_device_id argument in Linux 6.3
	decide NV_I2C_DRIVER_STRUCT_PROBE_WITHOUT_I2C_DEVICE_ID_ARG probe_noid \
'#include <linux/i2c.h>
void conftest_probe(struct i2c_driver *d);
void conftest_probe(struct i2c_driver *d) { d->probe(NULL); }'

	# i2c_driver.remove returns void since Linux 6.1
	decide NV_I2C_DRIVER_STRUCT_REMOVE_RETURN_TYPE_INT remove_int \
'#include <linux/i2c.h>
int conftest_remove(struct i2c_driver *d);
int conftest_remove(struct i2c_driver *d) { return d->remove(NULL); }'

	# struct v4l2_async_connection (Linux 6.5) - used by media/mc_common.h
	decide NV_V4L2_ASYNC_CONNECTION_STRUCT_PRESENT v4l2_async_conn \
'#include <media/v4l2-async.h>
unsigned long conftest_asc(void);
unsigned long conftest_asc(void) { return sizeof(struct v4l2_async_connection); }'

	# tegra_pmc_io_pad_power_enable(struct tegra_pmc *, enum tegra_io_pad):
	# upstream Linux 7.0, backported into the L4T 6.8 kernel. Adds the
	# `pmc` member to struct camera_common_data (media/camera_common.h).
	decide NV_TEGRA_PMC_IO_PAD_POWER_ENABLE_PRESENT pmc_io_pad \
'#include <soc/tegra/pmc.h>
int conftest_pmc(struct tegra_pmc *pmc);
int conftest_pmc(struct tegra_pmc *pmc) { return tegra_pmc_io_pad_power_enable(pmc, 0); }'

	echo "#endif"
} > "$OUT.tmp"
mv "$OUT.tmp" "$OUT"
echo "conftest: wrote $OUT" >&2
